package com.rexus.bandselector.data.root

import com.rexus.bandselector.data.util.BandMaskUtils
import java.io.File

object BootScriptGenerator {
    
    // Path for Magisk service.d
    // Usually /data/adb/service.d or /data/adb/post-fs-data.d
    private const val MAGISK_SERVICE_PATH = "/data/adb/service.d"
    private const val SCRIPT_NAME = "99_band_lock.sh"

    suspend fun installBootScript(vendorCmd: String) {
        if (!RootService.isRootAvailable()) return
        
        val scriptContent = """
            #!/system/bin/sh
            # Generated by Band Selector App
            
            # Wait for boot completion
            while [ "$(getprop sys.boot_completed)" != "1" ]; do
              sleep 1
            done
            
            # Safety Check: If safe_mode file exists (due to crash loop), exit.
            if [ -f /data/local/tmp/band_safe_mode ]; then
                exit 0
            fi
            
            sleep 10
            
            # Apply Lock
            $vendorCmd
            
            # Restart Radio to apply
            svc data disable
            svc data enable
        """.trimIndent()
        
        RootService.writeToFile("$MAGISK_SERVICE_PATH/$SCRIPT_NAME", scriptContent)
        RootService.run("chmod +x $MAGISK_SERVICE_PATH/$SCRIPT_NAME")
    }
    
    suspend fun clearBootScript() {
        RootService.run("rm $MAGISK_SERVICE_PATH/$SCRIPT_NAME")
    }
}
